#!/usr/bin/env lua

include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "os_imu",  
  published_frame = "base_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  publish_frame_projected_to_2d = false,
  use_pose_extrapolator = true,
  use_odometry = false,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 0,  
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 2,   
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,  
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1, 
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1., --1
  landmarks_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_3d = true

TRAJECTORY_BUILDER_3D.min_range = 0.3 -- minimal distance Point Cloud -> 0.3 ouster specs 
TRAJECTORY_BUILDER_3D.max_range = 120 -- maximal distance Point Cloud ->120 ouster specs  

TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 1
TRAJECTORY_BUILDER_3D.voxel_filter_size = .15  
TRAJECTORY_BUILDER_3D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_3D.real_time_correlative_scan_matcher.linear_search_window = 0.15
TRAJECTORY_BUILDER_3D.real_time_correlative_scan_matcher.angular_search_window = math.rad(.35) 

--Pose Graph
--Global SLAM
POSE_GRAPH.constraint_builder.sampling_ratio = 0.10 
POSE_GRAPH.constraint_builder.min_score = 0.8 
POSE_GRAPH.constraint_builder.max_constraint_distance = 120 
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.8
POSE_GRAPH.constraint_builder.loop_closure_translation_weight = 1.1e20
POSE_GRAPH.constraint_builder.loop_closure_rotation_weight = 1e20
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.linear_search_window = 10 
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.angular_search_window = math.rad(30.) 
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.branch_and_bound_depth = 10 
POSE_GRAPH.optimize_every_n_nodes = 0
POSE_GRAPH.optimization_problem.huber_scale = 5e2
POSE_GRAPH.optimization_problem.ceres_solver_options.max_num_iterations = 100

return options

